cmake_minimum_required(VERSION 4.3)
project(untitled C)

set(CMAKE_C_STANDARD 17)

add_executable(untitled
#        B3_String/ex3.c
#        B3_String/ex3_2.c
#        B3_String/ex41.c
        B3_String/ex4.c
        #        B2_Pointer/ex1.c
#        B2_Pointer/ex2.c
#        B2_Pointer/ex3.c
#        B2_Pointer/ex4.c
#        B2_Pointer/ex5.c
#        B2_Pointer/ex5_2.c
#        B3_String/strcpy.c
#        B3_String/strcat.c
#        B3_String/strstr.c
#        B3_String/strcmp.c
#        B3_String/memcpy.c
#        B3_String/memcmp.c
#        B3_String/memmove.c
#        B3_String/snprintf.c
#        B3_String/snscanf.c
        #        B3_String/string.c
#        B3_String/ex1.c
#        B3_String/ex2.c
#        B3_String/ex3.c
#        B2_Pointer/pointer.c
#        B2_Pointer/pointerArray.c
#        B2_Pointer/pointerSize.c
#        B2_Pointer/pointerArray2.c
#        B2_Pointer/pointerFunction.c
#        B2_Pointer/pointerSum.c
#        B1_Array/ex3.c
#        B1_Array/ex4.c
#        B1_Array/ex5.c
#        B2/pointer.c
#        B2/pointerArray.c
#        B2/pointerFunction.c
#        B1_Array/ex5.c
#        B1_Array/ex6.c
#        B1_Array/ex7.c
#        B1_Array/ex8.c
#        main.c
#        pt.c
#        number.c
)
